# Generated by Django 2.2.12 on 2020-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ord_list',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20, verbose_name='患者姓名')),
                ('dname', models.CharField(max_length=50, verbose_name='医生姓名或者id')),
                ('curedate', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=1, default=25.0, max_digits=3)),
            ],
            options={
                'db_table': 'ord_list',
            },
        ),
    ]
