# Generated by Django 2.2.12 on 2020-11-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuyue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ord_list',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
