# Generated by Django 2.2.12 on 2020-11-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=30, verbose_name='医生姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(choices=[('男', 'Male'), ('女', 'Female')], max_length=1, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('title', models.CharField(max_length=30, verbose_name='职称')),
                ('d_space', models.CharField(max_length=500, verbose_name='医生介绍')),
                ('surgery_weekday', models.CharField(max_length=100, verbose_name='出诊时间')),
                ('limit_visits', models.CharField(max_length=20, verbose_name='就诊人数上限')),
                ('dept', models.CharField(max_length=20, verbose_name='科室')),
                ('likes', models.CharField(choices=[('5', 'excellent'), ('4', 'great'), ('3', 'good'), ('2', 'normal'), ('1', 'bad')], max_length=1, verbose_name='喜爱')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('active', models.BooleanField(default=1, verbose_name='是否活跃')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20, verbose_name='科室名称')),
            ],
        ),
    ]
