# Generated by Django 2.2.12 on 2020-11-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20, verbose_name='科室名称')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=20, verbose_name='医生姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(max_length=1, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('title', models.CharField(max_length=20, verbose_name='职称')),
                ('d_space', models.CharField(max_length=500, verbose_name='医生介绍')),
                ('limit_visits', models.CharField(max_length=10, verbose_name='就诊人数上限')),
                ('dept', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.Hospital_department')),
            ],
        ),
    ]
