# Generated by Django 2.2.12 on 2020-11-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='workday',
            field=models.CharField(default='每天都要', max_length=100, verbose_name='排班'),
        ),
    ]
