# Generated by Django 2.2.12 on 2020-11-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_workday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='limit_visits',
            field=models.CharField(max_length=100, verbose_name='就诊人数上限'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='workday',
            field=models.CharField(max_length=100, verbose_name='排班安排'),
        ),
    ]
