# Generated by Django 2.2.12 on 2020-11-16 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(default=1, verbose_name='年龄')),
                ('gender', models.CharField(max_length=30, verbose_name='性别')),
                ('dname', models.CharField(max_length=30, verbose_name='科室')),
                ('title', models.CharField(max_length=20, verbose_name='职称')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('likes', models.CharField(max_length=50, verbose_name='喜好')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('intro', models.CharField(max_length=100, verbose_name='简介')),
                ('limit_visits', models.IntegerField(default=20, max_length=10, verbose_name='就诊人数上限')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday', models.CharField(default='每天都要', max_length=100, verbose_name='排班')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='update.Doctor')),
            ],
        ),
    ]
