# Generated by Django 2.2.12 on 2020-11-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='limit_visits',
            field=models.CharField(default=20, max_length=10, verbose_name='就诊人数上限'),
        ),
    ]
