# Generated by Django 2.2.12 on 2020-11-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_auto_20201116_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
