# Generated by Django 2.2.12 on 2020-11-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=models.CharField(max_length=20, verbose_name='姓名'), max_length=10, verbose_name='昵称'),
        ),
    ]
