# Generated by Django 2.2.12 on 2020-11-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201118_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=18, null=True, unique=True, verbose_name='身份证号'),
        ),
    ]
